<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct(); 
$query = [ 'id' => $_product->getId() ];
?>
<?php $buttonTitle = __('Print to PDF'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-printpdf" style="margin-bottom: 20px;">
    <div class="fieldset">
        <div class="">
        	<form action="<?php echo $block->getUrl("productprinter/index/index", ['_current' => false, '_use_rewrite' => false, '_query' => $query]); ?>" method="post" id="product_printpdf_form">
	            <button type="submit" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary tocart" id="product-printpdf-button">
	                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
	            </button>
            </form>
        </div>
    </div>
</div>
<?php endif; ?>

<script>
    require([
        'jquery',
        'mage/mage',
        'html2pdf',
//        'html2canvas',
        'Magento_Catalog/product/view/validation',
        'Dreamcode_ProductPrinter/js/print-product-to-pdf'
    ], function ($, mage, html2pdf) {
        'use strict';

    	$('#product_printpdf_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {

                var widget = $(form).printProductToPdf({
                    bindSubmit: false
                });

//                var element1 = $('body').find("#maincontent");
//                html2canvas(element1, {
//                    dpi: 450,
//                    letterRendering: true,
//                    allowTaint: true,
//                    logging:true
//                }).then(function(canvas) {
//                    document.body.appendChild(canvas);
//                });

                $("#print_product_info_pdf").show();
                $("#print_product_info_copyrignt").show();
                var element = document.getElementById('maincontent');
                html2pdf(element, {
                    margin:       0.3,
                    filename:     'myfile.pdf',
                    image:        { type: 'jpeg', quality: 0.98 },
                    html2canvas:  { dpi: 450, letterRendering: true },
                    jsPDF:        { unit: 'in', format: 'letter', orientation: 'landscape' }
                });

                $("#print_product_info_pdf").hide();
                $("#print_product_info_copyrignt").hide();

//                widget.printProductToPdf('submitForm', $(form));

                return false;
            }
        });
        
    });
</script>
