<?php
/**
 * Copyright © 2016 PlazaThemes.com. All rights reserved.
 *
 * @author PlazaThemes Team <contact@plazathemes.com>
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productModel = $objectManager->get('Magento\Catalog\Model\Product');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
		/*Grid*/
	if($viewMode == "grid"):
		/**
		 * Position for actions regarding image size changing in vde if needed
		 */
		$pos = $block->getPositioned(); 
		?>
		
		<div class="products wrapper products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
			<?php 
				$iterator = 1;   
			?>
			<ul class="products grid row">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?> 
				 
					<li class="products list items product-items item product col-sm-3 col-xs-6">
						<div class="item-inner product-item-info" data-container="product-grid">
							<?php
								$newFromDate = $_product->getNewsFromDate();
								$newToDate = $_product->getNewsToDate();                
								$now = date("Y-m-d H:m:s");
								// Get the Special Price
								$specialprice = $_product->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = $_product->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = $_product->getSpecialToDate();
								// Get Current date
								if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
								$_savePercent = 100 - round(($_product->getSpecialPrice() / $_product->getPrice())*100);
								echo "<div class='hot-sale'><span>-".$_savePercent."%</span><small>Off</small></div>";
								}else{
								if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
								?>
								<div class="label-pro-new"><span><?php echo __('new') ?></span></div>
								<?php
								}
								}
							?>
							<div class="image-container">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
								<div class="actions">
									<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<span><?php /* @escapeNotVerified */ echo __('WishList') ?></span>
											</a>
										<?php endif; ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#"
										   class="action tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<span><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
										</a>
									</div>
								</div>
							</div> 
							
							<div class="des product details product-item-details">
								<div class="product-name">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<strong class="product-item-name">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</strong>
									
								</div>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								
								
								<!-- Price Countdown Box -->
								<?php if($block->getEnabledCountdown()): ?>
									<?php if($block->setEnabledCountdownInList()): ?>
										<?php if($_product->getSpecialPrice() != null || $_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != ""): ?>
											<?php
												$product = $productModel->load($_product->getId());
											?>
											<?php if($product->getShowCountdown() == 1): ?>
												<div class="countbox-<?php echo $_product->getId(); ?> countdown-container">
													<div class='datetime'>
														<span class='day'><?php echo __('D') ?></span>
														<span class='hour'><?php echo __('H') ?></span>
														<span class='min'><?php echo __('M') ?></span>
														<span class='sec'><?php echo __('S') ?></span>
													</div>
												</div>

												<?php
													$toDate = $_product->getSpecialToDate();
													$fromDate = $_product->getSpecialFromDate();
													$_current_timer = time();
												?>

												<script type="text/javascript">
													var dthen<?php echo $_product->getId(); ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
													var start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
													var start_date = Date.parse(start);
													var dnow<?php echo $_product->getId(); ?> = new Date(start_date);

													var ddiff;
													if(CountStepper > 0) {
														ddiff= new Date((dnow<?php echo $_product->getId(); ?>)-(dthen<?php echo $_product->getId(); ?>));
													} else {
														ddiff = new Date((dthen<?php echo $_product->getId(); ?>)-(dnow<?php echo $_product->getId(); ?>));
													}

													<?php if(strtotime($fromDate) <= $_current_timer): ?>
														gsecs<?php echo $_product->getId(); ?> = Math.floor(ddiff.valueOf()/1000);
													<?php else: ?>
														gsecs<?php echo $_product->getId(); ?> = -1;
													<?php endif; ?>

													var iid<?php echo $_product->getId(); ?> = "countbox-<?php echo $_product->getId(); ?>";
													CountBack_slider(gsecs<?php echo $_product->getId(); ?>,"countbox-<?php echo $_product->getId(); ?>", <?php echo $_product->getId(); ?>);

													require(["jquery"], function($){
														$(document).ajaxComplete(function () {
															var dthen<?php echo $_product->getId(); ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
															var start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
															var start_date = Date.parse(start);
															var dnow<?php echo $_product->getId(); ?> = new Date(start_date);

															var ddiff;
															if(CountStepper > 0) {
																ddiff= new Date((dnow<?php echo $_product->getId(); ?>)-(dthen<?php echo $_product->getId(); ?>));
															} else {
																ddiff = new Date((dthen<?php echo $_product->getId(); ?>)-(dnow<?php echo $_product->getId(); ?>));
															}

															<?php if(strtotime($fromDate) <= $_current_timer): ?>
															gsecs<?php echo $_product->getId(); ?> = Math.floor(ddiff.valueOf()/1000);
															<?php else: ?>
															gsecs<?php echo $_product->getId(); ?> = -1;
															<?php endif; ?>

															var iid<?php echo $_product->getId(); ?> = "countbox-<?php echo $_product->getId(); ?>";
															CountBack_slider(gsecs<?php echo $_product->getId(); ?>,"countbox-<?php echo $_product->getId(); ?>", <?php echo $_product->getId(); ?>);
														});
													});
												</script>
											<?php endif; ?>
										<?php endif; ?>
									<?php endif; ?>
								<?php endif; ?>

								<?php if ($showDescription):?>
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
										   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
									</div>
								<?php endif; ?> 
							</div>
						</div>
					</li>  
				<?php endforeach; ?>
			</ul> 
		</div>
		<div class="toolbar-bottom">
			<?php echo $block->getToolbarHtml() ?>
		</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
    <?php
		/*List*/
	else:
		/**
		 * Position for actions regarding image size changing in vde if needed
		 */
		$pos = $block->getPositioned();
		?>



		<?php $categories = $block->getCategoryList(); if(count($categories)): ?>

<div class="page-title-wrapper category-title-wrapper">
    <h2 class="page-title category-title">
        <span class="base"><?php echo __('By Categories') ?></span>
    </h2>
</div>
<div class="products wrapper grid products-grid subcategories-listing">
    <ol class="products list items product-items">
        <?php foreach ($categories as $category): ?>
            <li class="item product product-item col-sm-3">
                <div class="product-item-info">
                	
					<?php //var_dump($category->getImageUrl()); die; ?>
					

                    <?php if ($category['thumbnail']): ?>
                        <a href="<?php echo $category->getUrl() ?>" title="<?php echo $category->getName() ?>"><img src="<?php echo $block->getCategoryThumbImage($category['thumbnail']); ?>" height="120" width="120" /></a>
                    <?php else: ?>
                        <a href="<?php echo $category->getUrl() ?>" title="<?php echo $category->getName() ?>"><img src="<?php echo $category->getImageUrl(); //$block->getViewFileUrl($block->getPlaceholderImage()); ?>" height="120" width="120" /></a>
                    <?php endif; ?>

                    <div class="product details product-item-details">
                        <strong class="product name product-item-name category-item-name">
                            <a href="<?php echo $category->getUrl() ?>" title="<?php echo $category->getName() ?>"><?php echo $category->getName() ?></a>
                        </strong>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>


<?php if($block->checkCategoryLevel() == true): ?>
		<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
			<?php $iterator = 1; ?>

			<div class="products list items product-items">
				<table class="table table-bordered table-hover cart table-responsive">
					<thead>
						<tr>
							<th>Diameter</th>
							<th>Width</th>
							<th>Capacity</th>
							<th>Hub Length</th>
							<th>Bearing</th>
							<th>Fits Axle</th>
							<th>Temp, Low</th>
							<th>Temp, high</th>
							<th>Wheel Number</th>
						</tr>
					</thead>
					<tbody>
						<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
						<?php foreach ($_productCollection as $_product): ?>
						<tr>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_diameter')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_width')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_capacity')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_hub_length')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_bearing')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('wheel_axle_diameter')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('temp_min')->getFrontend()->getValue($_product); ?></td>
							<td><?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('temp_max')->getFrontend()->getValue($_product); ?></td>
							<td>
								<strong><a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="Click here to learn more">
									<?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('sku')->getFrontend()->getValue($_product); ?>
								</a></strong>
							</td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
				
		</div>

		<div class="toolbar-bottom">
			<?php //echo $block->getToolbarHtml() ?>
		</div> 
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>

<?php endif; ?>


		
	<?php 
	endif;
	?>
<?php endif; ?>