<?php 


// $categoryFactory = $objectManager->create('Magento\Catalog\Helper\Category');
// $categoryFactory->getStoreCategories(false,false,true);

// $categorys = $this->getStoreCategories(false,false,true);
//   foreach($categorys as $category){
//      echo $category->getName();
//   }

?>


<div class="homepage-category-content-block">
	<div class="container">
		<div class="container-inner">
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/casters.html/">
							<img class="hp-fit-image" height="170" width="170"  src="http://casterexperts.com/media/catalog/category/caster-100.jpg">
						</a>
						<a href="http://dev2.casterexperts.com/casters.html/">Casters</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;">We carry a full line of Casters from Light Duty to Super Heavy Duty<br></span></h2><p></p>
					</div>

			</div>
			<hr>
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/wheels.html/">
	                        <img class="hp-fit-image" height="170" width="170"  src="http://casterexperts.com/media/catalog/category/TR-Wheels-265_1.png">
	                    </a>
						<a href="http://dev2.casterexperts.com/wheels.html/">Wheels</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;"><br></span></h2><p></p>
					</div>

			</div>

			<hr>
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/accessories.html/">
	                        <img class="hp-fit-image" height="170" width="170" src="http://casterexperts.com/media/catalog/category/FL-265_1.png">
	                    </a>
						<a href="http://dev2.casterexperts.com/accessories.html/">Accessories</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;"><br></span></h2><p></p>
					</div>

			</div>

			<hr>
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/levelers-glides.html/">
	                        <img class="hp-fit-image"  height="170" width="170" src="http://dev2.casterexperts.com/pub/static/frontend/genius/genius1/en_US/Magento_Catalog/images/product/placeholder/image.jpg">
	                    </a>
						<a href="http://dev2.casterexperts.com/levelers-glides.html/">Levelers &amp; Glides</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;">OEM Levelers <span style="font-family: terminal, monaco;">&amp;</span> Glides, Sockets <span style="font-family: terminal, monaco;">&amp;</span> Inserts<br></span></h2>
					</div>

			</div>

			<hr>
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/handtrucks-carts.html/">
	                        <img class="hp-fit-image"  height="170" width="170" src="http://dev2.casterexperts.com/pub/static/frontend/genius/genius1/en_US/Magento_Catalog/images/product/placeholder/image.jpg">
	                    </a>
						<a href="http://dev2.casterexperts.com/handtrucks-carts.html/">Handtrucks &amp; Carts</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;"></span></h2>
					</div>

			</div>
			
			<hr>
			<div class="row">

					<div class="col col-md-2 col-sm-12 col-xs-12 col-md-offset-2">
						<a href="http://dev2.casterexperts.com/parts.html//">
	                        <img class="hp-fit-image" height="170" width="170" src="http://dev2.casterexperts.com/pub/static/frontend/genius/genius1/en_US/Magento_Catalog/images/product/placeholder/image.jpg">
	                    </a>
						<a href="http://dev2.casterexperts.com/parts.html/">Parts</a>
					</div>

					<div class="col col-md-8 col-sm-12 col-xs-12">
		                <p></p><h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;">Bearings, Axles, Bushings, Washers and Spacers,</span></h2>
						<h2 style="text-align: left;"><span style="color: #000080; font-family: trebuchet ms,geneva; font-size: medium;">Rig Replacement Parts <span style="font-family: terminal, monaco;">&amp;</span> Brake Kits<br></span></h2><p></p>
					</div>

			</div>


		</div>
	</div>
</div>