<?php 
/**
 * @var $block \Dreamcode\Customize\Block\Category\ListCategory
 */
?>
<div class="row">
    <div id="dc_list_sub_category" class="products wrapper">

        <?php $categories = $block->getCategoryList(); if(count($categories)): ?>
            <?php $placeholderImage = $block->getViewFileUrl($block->getPlaceholderImage()); ?>
            <div class="page-title-wrapper category-title-wrapper">
                <h2 class="page-title category-title">
                    <span class="base"><?php echo __('By Categories') ?></span>
                </h2>
            </div>
            <div class="products wrapper grid products-grid subcategories-listing">
                <ol class="products list items product-items">
                    <?php foreach ($categories as $category): ?>
                        <?php $category_image = ($category->getImageUrl('thumb_nail') != '' ? $category->getImageUrl('thumb_nail') : $placeholderImage); ?>
                        <li class="item product product-item col-sm-3">
                            <div class="product-item-info">
                                <a href="<?php echo $block->escapeHtml($category->getUrl()); ?>" title="<?php echo $block->escapeHtml($category->getName()); ?>"><img src="<?php echo $category_image; ?>" height="120" width="120" /></a>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name category-item-name">
                                        <a href="<?php echo $block->escapeHtml($category->getUrl()); ?>" title="<?php echo $block->escapeHtml($category->getName()); ?>"><?php echo $block->escapeHtml($category->getName()); ?></a>
                                    </strong>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        <?php endif; ?>

    </div>
</div>
