<script type="text/javascript">
// <![CDATA[
    require([
        'jquery',
        'html2pdf',
        'domReady!'
    ], function ($, html2pdf) {
	    setTimeout(function(){
		  	$(function() {


                var contents = $(".page-wrapper").html();
                var frame1 = $('<iframe />');
                frame1[0].name = "frame1";
                frame1.css({ "position": "absolute", "top": "-1000000px" });
                $("body").append(frame1);
                var frameDoc = frame1[0].contentWindow ? frame1[0].contentWindow : frame1[0].contentDocument.document ? frame1[0].contentDocument.document : frame1[0].contentDocument;
                frameDoc.document.open();
                //Create a new HTML document.
                frameDoc.document.write('<html><head><title>DIV Contents</title>');
                frameDoc.document.write('</head><body>');
                //Append the external CSS file.
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/mage/calendar.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/styles-m.css" rel="stylesheet" type="text/css" />');
//                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/bootstrap.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/Dreamcode_ProductPrinter/css/bootstrap.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/bootstrap-theme.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/font-awesome.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/pe-icon-7-stroke.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/animate.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/style.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/custom-style.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/Plazathemes_Quickview/css/pt_quickview.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/mage/gallery/gallery.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/Plazathemes_Quickview/css/swatches.css" rel="stylesheet" type="text/css" />');





                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/Dreamcode_ProductPrinter/css/style.css"  rel="stylesheet" type="text/css" />');




                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/styles-l.css" rel="stylesheet" type="text/css" />');
//                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/print.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="http://local.dev/magento/dev2/pub/static/frontend/genius/genius1/en_US/css/owl.carousel.css" rel="stylesheet" type="text/css" />');
                frameDoc.document.write('<link href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700" rel="stylesheet" type="text/css" />');




                //Append the DIV contents.
                frameDoc.document.write(contents);
                frameDoc.document.write('</body></html>');
                frameDoc.document.close();
                setTimeout(function () {
//                    window.frames["frame1"].focus();
//                    window.frames["frame1"].print();
//                    frame1.remove();

                    html2canvas(document.body, {
                        onrendered: function(canvas) {
                            document.body.appendChild(canvas);
                        }
                    });

                    var element = document.getElementById('maincontent');
                    html2pdf(element);


                }, 500);



			    //window.print();
			});
		}, 3000);
    });




// ]]>
</script>

